const KEY="rozana_app_v2";
const SESSION_KEY="rozana_session";
const TELEGRAM_LOGIN_ENDPOINT="/api/telegram-login";
const WORKER_NATIONALITIES=["إثيوبيا","غانا","بوروندي","الفلبين","بنغلادش","نيبال","أوغندا","أخرى"];
const GUARANTOR_NATIONALITIES=["أردني","فلسطيني","سوري","عراقي","سعودي","كويتي","إماراتي","قطري","مصري","لبناني","أخرى"];
const COST_ITEMS=[
 ["unionStamp","ختم نقابة"],["insurance","التأمين"],["stamps","طوابع"],["workPermit","تصريح العمل"],["contract","العقد"],["contractDispatch","إرسالية العقود"],["visa","التأشيرة"],["airportDelivery","توصيل المطار"],["medical","الفحص الطبي"],["medicalExtras","مصاريف جانبية للفحص الطبي"],["photos","صور شخصية"],["residence","الإقامة"],["commission","العمولة"],["tax","الضريبة"],["otherExpenses","مصاريف جانبية"]
];
const initial={workers:[],guarantors:[],payments:[],expenses:[],followups:[],settings:{companyName:"روزنا الأردنية لاستخدام العاملين في المنازل",companyPhone:"",managerName:"المدير",managerEmail:"rasheedsaleh23@icloud.com",managerPassword:"Rasheed12345@",themeColor:"#1f7a5a",themeMode:"light",users:[]}};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||initial;
db={...initial,...db,settings:{...initial.settings,...(db.settings||{})}};
for(const k of ["workers","guarantors","payments","expenses","followups"])if(!Array.isArray(db[k]))db[k]=[];
db.payments.forEach(p=>{if(!p.status)p.status="paid";if(!p.source)p.source="legacy"});
if(!Array.isArray(db.settings.users))db.settings.users=[];
localStorage.setItem(KEY,JSON.stringify(db));
let currentUser=null,editingPaymentsWorkerId=null;
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])),uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random(),today=()=>new Date().toISOString().slice(0,10),num=v=>Math.max(0,Number(v)||0),money=n=>num(n).toFixed(2)+" د.أ",users=()=>db.settings.users||[],workerName=id=>db.workers.find(x=>x.id===id)?.name||"—";
function workerCost(w){return COST_ITEMS.reduce((s,[k])=>s+num(w.costs?.[k]),0)}
function workerPaid(id){return db.payments.filter(p=>p.workerId===id&&p.status!=="unpaid").reduce((s,p)=>s+num(p.amount),0)}
function workerRemaining(w){return Math.max(0,num(w.sale)-workerPaid(w.id))}
function paymentStatus(w){const sale=num(w.sale),paid=workerPaid(w.id);if(sale<=0&&paid<=0)return "غير محدد";if(paid<=0)return "غير مسدد";if(paid+0.005>=sale)return "مسدد";return "مدفوع جزئياً"}
function totals(){return db.workers.reduce((a,w)=>{a.sales+=num(w.sale);a.costs+=workerCost(w);a.profits+=num(w.sale)-workerCost(w);a.paid+=workerPaid(w.id);a.remaining+=workerRemaining(w);return a},{sales:0,costs:0,profits:0,paid:0,remaining:0})}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function renderAll(){const t=totals();$("workersCount").textContent=db.workers.length;$("activeCount").textContent=db.workers.filter(w=>w.status!=="غادرت").length;$("salesTotal").textContent=money(t.sales);$("costsTotal").textContent=money(t.costs);$("profitsTotal").textContent=money(t.profits);$("paymentsTotal").textContent=money(t.paid);$("remainingTotal").textContent=money(t.remaining);$("overdueTotal").textContent=db.workers.filter(w=>paymentStatus(w)==="غير مسدد"||paymentStatus(w)==="مدفوع جزئياً").length;$("paymentsPanelTotal").textContent=money(t.paid);$("remainingPanelTotal").textContent=money(t.remaining);$("paidWorkersCount").textContent=db.workers.filter(w=>paymentStatus(w)==="مسدد").length;$("unpaidWorkersCount").textContent=db.workers.filter(w=>paymentStatus(w)!=="مسدد").length;const et=db.expenses.reduce((a,e)=>a+num(e.amount),0);$("expensesPanelTotal").textContent=money(et);$("reportSales").textContent=money(t.sales);$("reportCosts").textContent=money(t.costs);$("reportProfits").textContent=money(t.profits);$("reportPayments").textContent=money(t.paid);$("reportRemaining").textContent=money(t.remaining);$("companyName").value=db.settings.companyName||"";$("companyPhone").value=db.settings.companyPhone||"";$("managerName").value=db.settings.managerName||"";$("managerEmail").value=db.settings.managerEmail||"";$("headerManagerName").textContent=db.settings.managerName||"المدير";$("brandName").textContent=(db.settings.companyName||"روزنا").split(" ")[0]||"روزنا";$("themeColor").value=db.settings.themeColor||"#1f7a5a";applyTheme();renderWorkers();renderGuarantors();renderPaymentSummary();renderExpenses();renderFollowups();renderUsers();fillWorkerSelects();updateTelegramStatus();}
function renderWorkers(){const q=$("workerSearch").value.trim().toLowerCase(),st=$("workerStatus").value,n=$("workerNationality").value;const rows=db.workers.filter(w=>(!q||[w.name,w.passport,w.phone,w.guarantorName].join(" ").toLowerCase().includes(q))&&(!st||w.status===st)&&(!n||w.nationality===n));$("workersTable").innerHTML=rows.map(w=>`<tr><td>${esc(w.name||"بدون اسم")}</td><td>${esc(w.nationality||"—")}</td><td>${esc(w.passport||"—")}</td><td>${esc(w.guarantorName||"—")}</td><td>${money(w.sale)}</td><td>${money(workerCost(w))}</td><td class="profit-cell">${money(num(w.sale)-workerCost(w))}</td><td><span class="status-pill ${paymentStatus(w)==="مسدد"?"paid":"unpaid"}">${paymentStatus(w)}</span><small class="subtle">باقي ${money(workerRemaining(w))}</small></td><td><button class="small-btn" onclick="editWorker('${w.id}')">تعديل</button><button class="small-btn" onclick="openWorkerPayments('${w.id}')">الدفعات</button><button class="small-btn danger" onclick="deleteWorker('${w.id}')">حذف</button></td></tr>`).join("")||'<tr><td colspan="9">لا توجد بيانات</td></tr>'}
function renderGuarantors(){const q=$("guarantorSearch").value.trim().toLowerCase(),n=$("guarantorNationalityFilter").value;const rows=db.guarantors.filter(g=>(!q||[g.name,g.phone].join(" ").toLowerCase().includes(q))&&(!n||g.nationality===n));$("guarantorsTable").innerHTML=rows.map(g=>`<tr><td>${esc(g.name||"بدون اسم")}</td><td>${esc(g.nationality||"—")}</td><td>${esc(g.phone||"—")}</td><td>${db.workers.filter(w=>w.guarantorName===g.name).length}</td><td><button class="small-btn" onclick="editGuarantor('${g.id}')">تعديل</button><button class="small-btn danger" onclick="deleteGuarantor('${g.id}')">حذف</button></td></tr>`).join("")||'<tr><td colspan="5">لا يوجد كفلاء</td></tr>'}
function renderPaymentSummary(){const rows=db.workers;$("paymentSummaryTable").innerHTML=rows.map(w=>`<tr><td>${esc(w.name||"بدون اسم")}</td><td>${money(w.sale)}</td><td>${money(workerPaid(w.id))}</td><td>${money(workerRemaining(w))}</td><td><span class="status-pill ${paymentStatus(w)==="مسدد"?"paid":"unpaid"}">${paymentStatus(w)}</span></td><td>${db.payments.filter(p=>p.workerId===w.id).length}</td><td><button class="small-btn" onclick="openWorkerPayments('${w.id}')">إدارة الدفعات</button></td></tr>`).join("")||'<tr><td colspan="7">لا توجد عاملات</td></tr>'}
function renderExpenses(){$("expensesTable").innerHTML=db.expenses.map(e=>`<tr><td>${esc(e.title||"—")}</td><td>${money(e.amount)}</td><td>${esc(e.date||"—")}</td><td>${esc(e.notes||"")}</td><td><button class="small-btn danger" onclick="deleteExpense('${e.id}')">حذف</button></td></tr>`).join("")||'<tr><td colspan="5">لا توجد مصاريف</td></tr>'}
function renderFollowups(){$("followupTable").innerHTML=db.followups.map(f=>`<tr><td>${esc(workerName(f.workerId))}</td><td>${esc(f.date||"—")}</td><td>${esc(f.type||"—")}</td><td>${esc(f.status||"—")}</td><td>${esc(f.notes||"")}</td><td><button class="small-btn danger" onclick="deleteFollowup('${f.id}')">حذف</button></td></tr>`).join("")||'<tr><td colspan="6">لا توجد متابعات</td></tr>'}
function fillWorkerSelects(){for(const id of ["pWorker","fWorker"]){const el=$(id);if(!el)continue;el.innerHTML=db.workers.map(w=>`<option value="${w.id}">${esc(w.name||"بدون اسم")} — ${esc(w.passport||"بدون جواز")}</option>`).join("")}}
function applyPermissions(u){document.querySelectorAll(".tab").forEach(t=>t.style.display=(u.role==="manager"||(u.permissions||[]).includes(t.dataset.tab))?"":"none")}
function findUser(email,pass){if(email===db.settings.managerEmail&&pass===db.settings.managerPassword)return{id:"manager",name:db.settings.managerName||"المدير",email,role:"manager",permissions:["workers","guarantors","payments","expenses","followup","reports","settings"]};return users().find(u=>u.email===email&&u.password===pass&&u.active!==false)||null}
function persistSession(u){localStorage.setItem(SESSION_KEY,JSON.stringify({email:u.email,role:u.role,name:u.name}))}
function showApp(u){currentUser=u;persistSession(u);$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");applyPermissions(u);renderAll()}
async function telegramSend(payload){try{const r=await fetch(TELEGRAM_LOGIN_ENDPOINT,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());return true}catch(e){console.error("Telegram:",e);return false}}
async function notifyTelegramLogin(u){const ok=await telegramSend({event:"login",name:u.name,email:u.email,role:u.role,time:new Date().toISOString()});if(!ok)$("loginError").textContent="تم الدخول، لكن تعذر إرسال تنبيه Telegram. راجع إعدادات Cloudflare."}
async function updateTelegramStatus(){const el=$("telegramStatus");if(!el)return;try{const r=await fetch(TELEGRAM_LOGIN_ENDPOINT,{method:"GET"});el.textContent=r.ok?"Telegram متصل بالواجهة":"Telegram يحتاج إعداد Cloudflare";el.style.color=r.ok?"var(--primary)":"#d97706"}catch{el.textContent="تعذر فحص Telegram من هذا الرابط"}}
$("loginBtn").onclick=()=>{const u=findUser($("email").value.trim(),$("password").value);if(u){$("loginError").textContent="";showApp(u);notifyTelegramLogin(u)}else $("loginError").textContent="البريد الإلكتروني أو كلمة المرور غير صحيحة."};
$("logoutBtn").onclick=()=>{localStorage.removeItem(SESSION_KEY);currentUser=null;$("appView").classList.add("hidden");$("loginView").classList.remove("hidden");$("password").value=""};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
["workerSearch","workerStatus","workerNationality"].forEach(id=>$(id).addEventListener("input",renderWorkers));["guarantorSearch","guarantorNationalityFilter"].forEach(id=>$(id).addEventListener("input",renderGuarantors));
function applyTheme(){document.body.classList.toggle("dark",db.settings.themeMode==="dark");$("themeToggle").textContent=db.settings.themeMode==="dark"?"☀️ نهاري":"🌙 ليلي";document.documentElement.style.setProperty("--primary",db.settings.themeColor||"#1f7a5a")}
$("themeToggle").onclick=()=>{db.settings.themeMode=db.settings.themeMode==="dark"?"light":"dark";save()};
function buildCostFields(){const box=$("costFields");box.innerHTML=COST_ITEMS.map(([key,label])=>`<div class="cost-item"><label>${label}</label><input class="cost-input" data-cost="${key}" type="number" min="0" step="0.01" inputmode="decimal" placeholder="0.00"></div>`).join("");document.querySelectorAll(".cost-input").forEach(i=>i.addEventListener("input",updateWorkerFinance))}
function updateWorkerFinance(){const cost=[...document.querySelectorAll(".cost-input")].reduce((s,i)=>s+num(i.value),0),sale=num($("wSale").value);$("wCostTotal").textContent=money(cost);$("wProfitTotal").textContent=money(sale-cost);updateInstallmentPreview()}
function getPlanRows(){return [...document.querySelectorAll("#installmentEditor .installment-row")].map(r=>({id:r.dataset.id||uid(),amount:num(r.querySelector(".inst-amount").value),date:r.querySelector(".inst-date").value,status:r.querySelector(".inst-status").value}))}
function renderPlanRows(rows,count){const box=$("installmentEditor");if($("wPaymentPlan").value!=="installments"){box.innerHTML='<div class="hint">اختَر «على دفعات» لإضافة عدد الدفعات وتواريخها.</div>';updateInstallmentPreview();return}const existing=rows||[];const n=Math.max(1,Number(count)||existing.length||1);const out=[];for(let i=0;i<n;i++){const r=existing[i]||{id:uid(),amount:0,date:"",status:"unpaid"};out.push(`<div class="installment-row" data-id="${r.id}"><div><label>الدفعة ${i+1}</label><input class="inst-amount" type="number" min="0" step="0.01" value="${r.amount||""}"></div><div><label>التاريخ</label><input class="inst-date" type="date" value="${r.date||""}"></div><div><label>الحالة</label><select class="inst-status"><option value="unpaid" ${r.status!=="paid"?"selected":""}>غير مسددة</option><option value="paid" ${r.status==="paid"?"selected":""}>مسددة</option></select></div><button type="button" class="remove-installment" title="حذف">×</button></div>`)}box.innerHTML=out.join("");box.querySelectorAll("input,select").forEach(x=>x.addEventListener("input",updateInstallmentPreview));box.querySelectorAll(".remove-installment").forEach(x=>x.onclick=()=>{x.closest(".installment-row").remove();$("wInstallmentCount").value=box.querySelectorAll(".installment-row").length;updateInstallmentPreview()});updateInstallmentPreview()}
function updateInstallmentPreview(){let rows=getPlanRows();let paid=rows.filter(r=>r.status==="paid").reduce((s,r)=>s+r.amount,0);if($("wPaymentPlan").value!=="installments")paid=workerPaid($("workerId").value);const sale=num($("wSale").value);$("wPaidTotal").textContent=money(paid);$("wRemainingTotal").textContent=money(Math.max(0,sale-paid));$("wPaymentStatus").textContent=paid<=0?(sale?"غير مسدد":"غير محدد"):(paid+0.005>=sale?"مسدد":"مدفوع جزئياً")}
function openWorkerForm(id){buildCostFields();const w=id?db.workers.find(x=>x.id===id):null;$('workerForm').reset();$("workerId").value=w?.id||"";$("workerDialogTitle").textContent=w?"تعديل ملف العاملة":"إضافة عاملة";$("wNationality").value=w?.nationality||"إثيوبيا";$("wGuarantorNationality").value=w?.guarantorNationality||"أردني";$("wStatus").value=w?.status||"متاحة";$("wName").value=w?.name||"";$("wPassport").value=w?.passport||"";$("wGuarantorName").value=w?.guarantorName||"";$("wPhone").value=w?.phone||"";$("wDob").value=w?.dob||"";$("wNotes").value=w?.notes||"";$("wSale").value=w?.sale||"";document.querySelectorAll(".cost-input").forEach(i=>i.value=w?.costs?.[i.dataset.cost]??"");$("wPaymentPlan").value=w?.paymentPlan||"full";const rows=w?.installments||[];$("wInstallmentCount").value=rows.length||1;renderPlanRows(rows,$("wInstallmentCount").value);updateWorkerFinance();$("workerDialog").showModal()}
$("addWorker").onclick=()=>openWorkerForm();window.editWorker=id=>openWorkerForm(id);
$("wPaymentPlan").onchange=()=>renderPlanRows($("wPaymentPlan").value==="installments"?getPlanRows():[],$("wInstallmentCount").value);$("wInstallmentCount").oninput=()=>renderPlanRows(getPlanRows(),$("wInstallmentCount").value);$("wSale").addEventListener("input",updateWorkerFinance);
$("workerForm").addEventListener("submit",e=>{e.preventDefault();const id=$("workerId").value,costs={};document.querySelectorAll(".cost-input").forEach(i=>costs[i.dataset.cost]=num(i.value));const plan=$("wPaymentPlan").value;let installments=getPlanRows();if(plan==="full"){installments=[]}else if(installments.length===0){installments=[{id:uid(),amount:num($("wSale").value),date:"",status:"unpaid"}]};const data={name:$("wName").value.trim(),nationality:$("wNationality").value,passport:$("wPassport").value.trim(),guarantorName:$("wGuarantorName").value.trim(),guarantorNationality:$("wGuarantorNationality").value,phone:$("wPhone").value.trim(),status:$("wStatus").value,dob:$("wDob").value,notes:$("wNotes").value,sale:num($("wSale").value),costs,paymentPlan:plan,installments,created:id?(db.workers.find(x=>x.id===id)?.created||today()):today()};if(id){Object.assign(db.workers.find(x=>x.id===id),data);if(plan==="installments")syncInstallments(id,installments);else db.payments=db.payments.filter(p=>!(p.workerId===id&&p.source==="plan"))}else{const newId=uid();db.workers.push({id:newId,...data});if(plan==="installments")syncInstallments(newId,installments)}$("workerDialog").close();save()});
function syncInstallments(workerId,rows){db.payments=db.payments.filter(p=>!(p.workerId===workerId&&p.source==="plan"));rows.forEach(r=>db.payments.push({id:r.id||uid(),workerId,amount:r.amount,date:r.date||"",method:"خطة تسديد",notes:"دفعة من خطة التسديد",status:r.status==="paid"?"paid":"unpaid",source:"plan"}))}
$("cancelWorker").onclick=()=>{$("workerForm").reset();$("workerDialog").close()};window.deleteWorker=id=>{if(confirm("حذف ملف العاملة؟ سيتم حذف دفعاتها ومتابعاتها أيضاً.")){db.workers=db.workers.filter(x=>x.id!==id);db.payments=db.payments.filter(x=>x.workerId!==id);db.followups=db.followups.filter(x=>x.workerId!==id);save()}};
function openWorkerPayments(id){editingPaymentsWorkerId=id;const w=db.workers.find(x=>x.id===id);if(!w)return;$("paymentsWorkerId").value=id;$("paymentsDialogTitle").textContent="دفعات: "+(w.name||"بدون اسم");$("workerPaymentInfo").innerHTML=`سعر البيع: <b>${money(w.sale)}</b> &nbsp; | &nbsp; المدفوع: <b>${money(workerPaid(id))}</b> &nbsp; | &nbsp; المتبقي: <b>${money(workerRemaining(w))}</b> &nbsp; | &nbsp; الحالة: <b>${paymentStatus(w)}</b>`;renderPaymentRows();$("paymentsDialog").showModal()}
window.openWorkerPayments=openWorkerPayments;
function renderPaymentRows(){const rows=db.payments.filter(p=>p.workerId===editingPaymentsWorkerId);$("installmentRows").innerHTML=rows.map((p,i)=>`<div class="payment-row" data-id="${p.id}"><div><label>المبلغ</label><input class="pay-amount" type="number" min="0" step="0.01" value="${p.amount||""}"></div><div><label>التاريخ</label><input class="pay-date" type="date" value="${p.date||""}"></div><div><label>الطريقة</label><select class="pay-method"><option ${p.method==="نقدي"?"selected":""}>نقدي</option><option ${p.method==="تحويل بنكي"?"selected":""}>تحويل بنكي</option><option ${p.method==="كليك"?"selected":""}>كليك</option><option ${p.method==="خطة تسديد"?"selected":""}>خطة تسديد</option><option ${p.method==="أخرى"?"selected":""}>أخرى</option></select></div><div><label>الحالة</label><select class="pay-status"><option value="unpaid" ${p.status!=="paid"?"selected":""}>غير مسددة</option><option value="paid" ${p.status==="paid"?"selected":""}>مسددة</option></select></div><button type="button" class="delete-row" onclick="removePaymentRow('${p.id}')">حذف</button></div>`).join("");if(!rows.length)$("installmentRows").innerHTML='<div class="hint">لا توجد دفعات مسجلة لهذه العاملة.</div>';updateDialogPaymentTotals();document.querySelectorAll("#installmentRows input,#installmentRows select").forEach(x=>x.addEventListener("input",updateDialogPaymentTotals))}
window.removePaymentRow=id=>{if(confirm("حذف هذه الدفعة فقط؟")){db.payments=db.payments.filter(p=>p.id!==id);renderPaymentRows();renderAll()}};
function updateDialogPaymentTotals(){const rows=[...document.querySelectorAll(".payment-row")];const paid=rows.filter(r=>r.querySelector(".pay-status").value==="paid").reduce((s,r)=>s+num(r.querySelector(".pay-amount").value),0),w=db.workers.find(x=>x.id===editingPaymentsWorkerId),sale=num(w?.sale),rem=Math.max(0,sale-paid);$("dialogPaidTotal").textContent=money(paid);$("dialogRemainingTotal").textContent=money(rem);$("dialogPaymentStatus").textContent=paid<=0?(sale?"غير مسدد":"غير محدد"):(paid+0.005>=sale?"مسدد":"مدفوع جزئياً")}
$("addInstallment").onclick=()=>{if(!editingPaymentsWorkerId)return;db.payments.push({id:uid(),workerId:editingPaymentsWorkerId,amount:0,date:today(),method:"نقدي",notes:"",status:"unpaid",source:"manual"});renderPaymentRows();renderAll()};
$("paymentsForm").addEventListener("submit",e=>{e.preventDefault();document.querySelectorAll(".payment-row").forEach(r=>{const p=db.payments.find(x=>x.id===r.dataset.id);if(p){p.amount=num(r.querySelector(".pay-amount").value);p.date=r.querySelector(".pay-date").value;p.method=r.querySelector(".pay-method").value;p.status=r.querySelector(".pay-status").value}});const w=db.workers.find(x=>x.id===editingPaymentsWorkerId);if(w){w.installments=db.payments.filter(p=>p.workerId===w.id).map(p=>({id:p.id,amount:p.amount,date:p.date,status:p.status}));w.paymentPlan=w.installments.length?"installments":"full"}$("paymentsDialog").close();save()});$("cancelPayments").onclick=()=>$("paymentsDialog").close();$("openWorkerPayments").onclick=()=>{const id=$("workerId").value;if(id){$("workerDialog").close();openWorkerPayments(id)}};
$("addGuarantor").onclick=()=>{$("guarantorForm").reset();$("gId").value="";$("guarantorDialog").showModal()};$("guarantorForm").addEventListener("submit",e=>{e.preventDefault();const id=$("gId").value,data={name:$("gName").value.trim(),nationality:$("gNationality").value,phone:$("gPhone").value.trim(),notes:$("gNotes").value};if(id)Object.assign(db.guarantors.find(x=>x.id===id),data);else db.guarantors.push({id:uid(),...data});$("guarantorDialog").close();save()});window.editGuarantor=id=>{const g=db.guarantors.find(x=>x.id===id);if(!g)return;$("gId").value=id;$("gName").value=g.name||"";$("gNationality").value=g.nationality||"أردني";$("gPhone").value=g.phone||"";$("gNotes").value=g.notes||"";$("guarantorDialog").showModal()};window.deleteGuarantor=id=>{if(confirm("حذف الكفيل؟")){db.guarantors=db.guarantors.filter(x=>x.id!==id);save()}};$("cancelGuarantor").onclick=()=>$("guarantorDialog").close();
$("addPayment").onclick=()=>{fillWorkerSelects();$("paymentForm").reset();$("pDate").value=today();$("paymentDialog").showModal()};$("paymentForm").addEventListener("submit",e=>{e.preventDefault();if(!$("pWorker").value)return alert("أضف عاملة أولاً");db.payments.push({id:uid(),workerId:$("pWorker").value,amount:num($("pAmount").value),method:$("pMethod").value,date:$("pDate").value,notes:$("pNotes").value,status:"paid",source:"manual"});$("paymentDialog").close();save()});$("cancelPayment").onclick=()=>$("paymentDialog").close();
$("addExpense").onclick=()=>{$("expenseForm").reset();$("eDate").value=today();$("expenseDialog").showModal()};$("expenseForm").addEventListener("submit",e=>{e.preventDefault();if(!$("eTitle").value.trim())return alert("أدخل بيان المصروف");db.expenses.push({id:uid(),title:$("eTitle").value,amount:num($("eAmount").value),date:$("eDate").value,notes:$("eNotes").value});$("expenseDialog").close();save()});window.deleteExpense=id=>{if(confirm("حذف المصروف؟")){db.expenses=db.expenses.filter(x=>x.id!==id);save()}};$("cancelExpense").onclick=()=>$("expenseDialog").close();
$("addFollowup").onclick=()=>{fillWorkerSelects();$("followupForm").reset();$("fDate").value=today();$("followupDialog").showModal()};$("followupForm").addEventListener("submit",e=>{e.preventDefault();if(!$("fWorker").value)return alert("أضف عاملة أولاً");db.followups.push({id:uid(),workerId:$("fWorker").value,date:$("fDate").value,type:$("fType").value,status:$("fStatus").value,notes:$("fNotes").value});$("followupDialog").close();save()});window.deleteFollowup=id=>{if(confirm("حذف المتابعة؟")){db.followups=db.followups.filter(x=>x.id!==id);save()}};$("cancelFollowup").onclick=()=>$("followupDialog").close();
$("saveSettings").onclick=()=>{db.settings.companyName=$("companyName").value;db.settings.companyPhone=$("companyPhone").value;save();alert("تم الحفظ")};$("saveManager").onclick=()=>{const email=$("managerEmail").value.trim();if(!email)return alert("البريد مطلوب");db.settings.managerName=$("managerName").value.trim()||"المدير";db.settings.managerEmail=email;save();alert("تم حفظ بيانات المدير")};$("addUser").onclick=()=>{const name=$("newUserName").value.trim(),email=$("newUserEmail").value.trim(),password=$("newUserPassword").value,role=$("newUserRole").value,permissions=[...document.querySelectorAll(".perm:checked")].map(x=>x.value);if(!name||!email||password.length<6)return alert("أدخل الاسم والبريد وكلمة مرور من 6 أحرف على الأقل");if(email.toLowerCase()===db.settings.managerEmail.toLowerCase()||users().some(u=>u.email.toLowerCase()===email.toLowerCase()))return alert("البريد مستخدم مسبقًا");db.settings.users.push({id:uid(),name,email,password,role,permissions,active:true});save();$("newUserName").value="";$("newUserEmail").value="";$("newUserPassword").value="";alert("تمت إضافة الموظف")};
function renderUsers(){$("usersTable").innerHTML=users().map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${u.role==="accounting"?"حسابات":u.role==="viewer"?"مشاهد":"موظف"}</td><td class="user-perm">${(u.permissions||[]).join("، ")}</td><td><button class="small-btn" onclick="editUser('${u.id}')">تعديل</button><button class="small-btn danger" onclick="deleteUser('${u.id}')">حذف</button></td></tr>`).join("")||'<tr><td colspan="5">لا يوجد موظفون</td></tr>'}window.editUser=id=>{const u=users().find(x=>x.id===id);if(!u)return;const n=prompt("اسم الموظف",u.name),e=prompt("البريد الإلكتروني",u.email);if(n===null||e===null)return;const r=prompt("الدور: employee / accounting / viewer",u.role)||u.role,p=prompt("الصلاحيات: workers,guarantors,payments,expenses,followup,reports,settings",(u.permissions||[]).join(","));if(!n.trim()||!e.trim())return;if(users().some(x=>x.id!==id&&x.email.toLowerCase()===e.trim().toLowerCase())||e.trim().toLowerCase()===db.settings.managerEmail.toLowerCase())return alert("البريد مستخدم مسبقًا");u.name=n.trim();u.email=e.trim();u.role=["employee","accounting","viewer"].includes(r)?r:"employee";u.permissions=(p||"").split(",").map(x=>x.trim()).filter(Boolean);const pw=prompt("كلمة مرور جديدة؟ اتركها فارغة للإبقاء على الحالية","");if(pw){if(pw.length<6)return alert("كلمة المرور يجب أن تكون 6 أحرف على الأقل");u.password=pw}save()};window.deleteUser=id=>{if(confirm("حذف الموظف؟")){db.settings.users=users().filter(x=>x.id!==id);save()}};
$("changePassword").onclick=()=>{if(currentUser?.role!=="manager")return alert("تغيير كلمة المرور متاح للمدير فقط");if($("currentPassword").value!==db.settings.managerPassword)return alert("كلمة المرور الحالية غير صحيحة");if($("newPassword").value.length<6||$("newPassword").value!==$("confirmPassword").value)return alert("كلمة المرور الجديدة غير صحيحة");db.settings.managerPassword=$("newPassword").value;save();alert("تم تغيير كلمة المرور")};$("saveTheme").onclick=()=>{db.settings.themeColor=$("themeColor").value;save();alert("تم حفظ اللون")};$("testTelegram").onclick=async()=>{const ok=await telegramSend({event:"test",name:currentUser?.name||"",email:currentUser?.email||"",role:currentUser?.role||"",time:new Date().toISOString()});alert(ok?"تم إرسال رسالة الاختبار إلى Telegram":"فشل الإرسال. تأكد من TELEGRAM_BOT_TOKEN و TELEGRAM_CHAT_ID في Cloudflare")};
$("exportData").onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="rozana-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$("importData").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);db={...initial,...x,settings:{...initial.settings,...(x.settings||{})}};for(const k of ["workers","guarantors","payments","expenses","followups"])if(!Array.isArray(db[k]))db[k]=[];
db.payments.forEach(p=>{if(!p.status)p.status="paid";if(!p.source)p.source="legacy"});delete db.contracts;save();alert("تم الاستيراد") }catch{alert("الملف غير صالح")}};r.readAsText(f)};
function report(type){const t=totals();let html="",company=esc(db.settings.companyName);if(type==="workers"||type==="all")html+=`<h2>العاملات</h2><table><tr><th>الاسم</th><th>الجنسية</th><th>الجواز</th><th>البيع</th><th>التكلفة</th><th>الربح</th><th>التسديد</th><th>المتبقي</th></tr>${db.workers.map(w=>`<tr><td>${esc(w.name)}</td><td>${esc(w.nationality)}</td><td>${esc(w.passport)}</td><td>${money(w.sale)}</td><td>${money(workerCost(w))}</td><td>${money(num(w.sale)-workerCost(w))}</td><td>${paymentStatus(w)}</td><td>${money(workerRemaining(w))}</td></tr>`).join("")}</table>`;if(type==="finance"||type==="all")html+=`<h2>الملخص المالي</h2><p>إجمالي البيع: ${money(t.sales)} | التكلفة: ${money(t.costs)} | الربح: ${money(t.profits)} | المدفوع: ${money(t.paid)} | المتبقي: ${money(t.remaining)}</p>`;if(type==="payments"||type==="all")html+=`<h2>التسديد</h2><table><tr><th>العاملة</th><th>المبلغ</th><th>الحالة</th><th>التاريخ</th><th>الطريقة</th></tr>${db.payments.map(p=>`<tr><td>${esc(workerName(p.workerId))}</td><td>${money(p.amount)}</td><td>${p.status==="paid"?"مسددة":"غير مسددة"}</td><td>${esc(p.date)}</td><td>${esc(p.method)}</td></tr>`).join("")}</table>`;const w=window.open("","_blank");if(!w)return alert("المتصفح منع فتح صفحة التقرير");w.document.write(`<html dir="rtl"><head><meta charset="utf-8"><title>تقرير روزنا</title><style>body{font-family:Arial;padding:30px}table{width:100%;border-collapse:collapse;margin:12px 0 25px}th,td{border:1px solid #bbb;padding:8px;text-align:right}th{background:#eee}.print{padding:10px 16px}@media print{.print{display:none}}</style></head><body><button class="print" onclick="print()">طباعة / حفظ PDF</button><h1>${company}</h1><div>تاريخ التقرير: ${today()}</div>${html}</body></html>`);w.document.close()}
document.querySelectorAll(".report-card").forEach(b=>b.onclick=()=>report(b.dataset.report));
buildCostFields();applyTheme();
const session=localStorage.getItem(SESSION_KEY);if(session)try{const s=JSON.parse(session),u=s.role==="manager"?{email:db.settings.managerEmail,name:db.settings.managerName,role:"manager",permissions:["workers","guarantors","payments","expenses","followup","reports","settings"]}:users().find(x=>x.email===s.email);if(u)showApp(u);else localStorage.removeItem(SESSION_KEY)}catch{localStorage.removeItem(SESSION_KEY)}
